---
- name: check telegraf existence
  stat: path=/etc/init.d/telegraf
  register: telegraf_binary
  ignore_errors: True

- name: download telegraf archive
  get_url: url=https://dl.influxdata.com/telegraf/releases/telegraf_{{ telegraf.version }}_amd64.deb dest=/tmp/telegraf.deb
  when: not telegraf_binary.stat.exists

- name: install telegraf packages
  apt: deb=/tmp/telegraf.deb
  when: not telegraf_binary.stat.exists
  notify: start telegraf

- name: copy telegraf conf
  template: src=telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: enable telegraf on boot
  systemd: name=telegraf enabled=yes masked=no
